### ISSUE TITLE
SIBR extension source code

### ISSUE THREAD

**Issue by MrNeRF** [oppo-us-research/SpacetimeGaussians#1]
Hey,
Thx for the wonderful work! Are you planning to release the extender SIBR source code? I think your released binary targets windows which does not work under linux. I also very much like to compile code myself. Any plans for releasing it? If you don't want to share it publicly, I would also appreciate to get it for my personal use so I can share some tests on twitter with your research results - if you are interested.

**Comment by lizhan17** [comment]
Thank you for your interest in our work! We are indeed planning to release the source code for the viewer. Please stay tuned for updates.

**Comment by dlazares** [comment]
source code would be awesome. I'm running into a memory leak error on some scenes and not able to debug it further
```
\code\gaussian-splatting-release-poly-lite\SIBR_viewers_poly_lite\src\projects\gaussianviewer\renderer\GaussianView.cpp
                        LINE 716, FUNC sibr::GaussianView::onRenderIBR
                        A CUDA error occurred during rendering:an illegal memory access was encountered. Please rerun in Debug to find the exact line!
```

**Comment by lizhan17** [comment]
Hi dlazares,
Yes, for some scenes contain the guided sampling, the viewer will not be compatible to the guided sampling after you see the scene through the viewer, throwing a cuda memory access error. I am working on the viewer. You can select the other scenes or set "--emsstart 30000" to disable the guided sampling to view the scene through the viewer. The test script should work with guided sampling anyway

**Comment by dlazares** [comment]
oh sweet, thanks for the quick response and congrats on a great paper!

**Comment by lizhan17** [comment]
> > Hi dlazares, for some scenes contain the guided sampling, the viewer will not be compatible to the guided sampling after you see the scene through the viewer, throwing a cuda memory access error. I am working on the viewer. You can select the other scenes or set "--emsstart 30000" to disable the guided sampling to view the scene through the viewer. The test script should work with guided sampling anyway
> 
> 
> 
> @lizhan17 I'm facing the same "illegal memory access" error when viewing self-trained scenes with the viewer. I confirmed that all three pretrained scenes given on huggingface worked fine in the viewer. However, when viewing a self-trained neural3dv scene (e.g. `coffee_martini` or `flame_salmon_1`, with either 'full' or 'lite' config), the viewer renders the first frame and then quits due to illegal memory access. I've tried to set "--emsstart 30000" but the problem persists. 
> 
> 
> 
> Please kindly give some suggestions on fixing this.

our viewer only work with lite model.

You can set line 258 in train.py with if false to disable ems.

**Comment by JiamingSuen** [comment]
> our viewer only work with lite model.
> You can set line 258 in train.py with if false to disable ems.

@lizhan17 Thanks for the reply. It worked after disabling ems. It would be nice if the viewer code could be released sooner.

**Comment by lizhan17** [comment]
viewer is reuploaded. The compatibility for guided sampling in the viewer should be fixed.

**Comment by lijenicol** [comment]
@lizhan17 Do you have an ETA of when we can expect the viewer source code? It would be great to be able to build this on linux!

**Comment by lizhan17** [comment]
> @lizhan17 Do you have an ETA of when we can expect the viewer source code? It would be great to be able to build this on linux!

viewer source code can be released by the end of this month.

**Comment by lizhan17** [comment]
Sourc code of Viewer is released.

**Comment by lijenicol** [comment]
Thank you @lizhan17 !
