### ISSUE TITLE
Unable to run the real-time viewer

### ISSUE THREAD

**Issue by THUSlll** [oppo-us-research/SpacetimeGaussians#14]
Hello, thank you very much for your work and for sharing it.！
I have successfully trained a model and am trying to use the real-time viewer to inspect it. However, my viewer is not running.
<img width="639" alt="1705331680732" src="https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/7c468781-b4c7-422d-91b7-df5cef0777b3">
It seems that, as shown in the image, despite my attempts, only ”SIBR_gaussianViewer_app_rwdi.exe“ is not running. The other executables can run successfully. However, when I try to run ”SIBR_gaussianViewer_app_rwdi.exe“, there is no output, and no error messages are displayed.
I look forward to your reply.

**Comment by THUSlll** [comment]
![1705332051803](https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/32a82aef-21d9-487f-b034-4e4b0ec0ada8)

**Comment by THUSlll** [comment]
I switched from PowerShell to CMD to run it, and this time it threw an error: the system says it can't find cudart64_110.dll. However, I saw in the project documentation that CUDA version >= 11.0 should work. Do you know what the problem might be? Thank you!

**Comment by lizhan17** [comment]
> I switched from PowerShell to CMD to run it, and this time it threw an error: the system says it can't find cudart64_110.dll. However, I saw in the project documentation that CUDA version >= 11.0 should work. Do you know what the problem might be? Thank you!

Hi,
Did you install the cuda toolkit?

**Comment by lizhan17** [comment]
> ![1705332051803](https://private-user-images.githubusercontent.com/87744829/296797709-32a82aef-21d9-487f-b034-4e4b0ec0ada8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDI3NzEsIm5iZiI6MTcwNTM0MjQ3MSwicGF0aCI6Ii84Nzc0NDgyOS8yOTY3OTc3MDktMzJhODJhZWYtMjFkOS00ODdmLWIwMzQtNGU0YjBlYzBhZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2M5OTM5NjkwYmJkMWU2MGMwNGRlZjA5NzZjNjhkZjcxY2NiMTcxYjc0MWU1YTU0MmQ0ZjYzYWM1MGE2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PztagL2-XcO7g4-X47WLYH3MFF_zBOUORVSOCWSJ6Hw) My CUDA version is 12.3, and I can successfully run the 3DGS real-time viewer. I'm not sure why it's not working this time. Thank you!

Hi I notice that you are viewing through the coffee martini. I currently find that 
For the scene like coffee martini which contains the error sampling, the viewer will not be compatible to the guided sampling after you see the scene through the viewer, throwing a cuda memory acess error. I am working on the viewer. You can select set the other scenes or set "--emsstart 30000" to disable the guided sampling to view the scene through the viewer.  The test script should work with guided sampling anyway.

**Comment by THUSlll** [comment]
> > ![1705332051803](https://private-user-images.githubusercontent.com/87744829/296797709-32a82aef-21d9-487f-b034-4e4b0ec0ada8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDI3NzEsIm5iZiI6MTcwNTM0MjQ3MSwicGF0aCI6Ii84Nzc0NDgyOS8yOTY3OTc3MDktMzJhODJhZWYtMjFkOS00ODdmLWIwMzQtNGU0YjBlYzBhZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2M5OTM5NjkwYmJkMWU2MGMwNGRlZjA5NzZjNjhkZjcxY2NiMTcxYjc0MWU1YTU0MmQ0ZjYzYWM1MGE2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PztagL2-XcO7g4-X47WLYH3MFF_zBOUORVSOCWSJ6Hw) My CUDA version is 12.3, and I can successfully run the 3DGS real-time viewer. I'm not sure why it's not working this time. Thank you!
> 
> Hi I notice that you are viewing through the coffee martini. I currently find that For the scene like coffee martini which contains the guided sampling, the viewer will not be compatible to the guided sampling after you see the scene through the viewer, throwing a cuda memory access error. We are working on the viewer. You can select the other scenes or set "--emsstart 30000" to disable the guided sampling to view the scene through the viewer. The test script should work with guided sampling anyway.

![1705378500597](https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/857dae62-d901-4652-8804-11399f6ddd79)

I've installed the CUDA toolkit version 12.3, and I can obtain results by using 'nvcc -V'. According to your suggestion, I will try the method of disabling guided sampling and training other scenes. Anyway, thank you very much for your response!

**Comment by lizhan17** [comment]
> > > ![1705332051803](https://private-user-images.githubusercontent.com/87744829/296797709-32a82aef-21d9-487f-b034-4e4b0ec0ada8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDI3NzEsIm5iZiI6MTcwNTM0MjQ3MSwicGF0aCI6Ii84Nzc0NDgyOS8yOTY3OTc3MDktMzJhODJhZWYtMjFkOS00ODdmLWIwMzQtNGU0YjBlYzBhZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2M5OTM5NjkwYmJkMWU2MGMwNGRlZjA5NzZjNjhkZjcxY2NiMTcxYjc0MWU1YTU0MmQ0ZjYzYWM1MGE2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PztagL2-XcO7g4-X47WLYH3MFF_zBOUORVSOCWSJ6Hw) My CUDA version is 12.3, and I can successfully run the 3DGS real-time viewer. I'm not sure why it's not working this time. Thank you!
> > 
> > 
> > Hi I notice that you are viewing through the coffee martini. I currently find that For the scene like coffee martini which contains the guided sampling, the viewer will not be compatible to the guided sampling after you see the scene through the viewer, throwing a cuda memory access error. We are working on the viewer. You can select the other scenes or set "--emsstart 30000" to disable the guided sampling to view the scene through the viewer. The test script should work with guided sampling anyway.
> 
> ![1705378500597](https://private-user-images.githubusercontent.com/87744829/296930085-857dae62-d901-4652-8804-11399f6ddd79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODA4NTIsIm5iZiI6MTcwNTM4MDU1MiwicGF0aCI6Ii84Nzc0NDgyOS8yOTY5MzAwODUtODU3ZGFlNjItZDkwMS00NjUyLTg4MDQtMTEzOTlmNmRkZDc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0NDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYzIyMDc1NGM1N2Y2YjRjNmI0NTU2OGRmYzQ1MTc5ZjNlMGFiZTNlNjcwMWM4MDE0MTg3N2M4YjI4MjhiNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RR6gTbthxvvtziyJWkMTDyFMwP3S2YGXFa62-KE6yx0)
> 
> I've installed the CUDA toolkit version 12.3, and I can obtain results by using 'nvcc -V'. According to your suggestion, I will try the method of disabling guided sampling and training other scenes. Anyway, thank you very much for your response!

Hi, i  think even with the guided sampling you can still see the scene in the viewer. although it is not stable. Did you miss the .exe  in the command ? you can try this 

```
C:\xxx\bin\SIBR_gaussianViewer_app_rwdi.exe --iteration 7000 --iteration 30000 --m C:\xxx\coffee_matini
```

**Comment by THUSlll** [comment]
![1705381058795](https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/4c3cd202-8cbb-4524-9030-f5dadf963b6f)
<img width="340" alt="1705381138738" src="https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/7c6cb50c-4170-48dc-8fc7-81d641d47498">
![1705381420501](https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/d196988d-0527-4f2c-b2bc-a852cfc6654b)

I used to omit the 'exe' in the 3DGS viewer, and it seems that's not the cause of the issue. I tried the other three datasets on the viewer download page, but none of them worked. Perhaps it's still a CUDA version problem？

**Comment by THUSlll** [comment]
> > > > ![1705332051803](https://private-user-images.githubusercontent.com/87744829/296797709-32a82aef-21d9-487f-b034-4e4b0ec0ada8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDI3NzEsIm5iZiI6MTcwNTM0MjQ3MSwicGF0aCI6Ii84Nzc0NDgyOS8yOTY3OTc3MDktMzJhODJhZWYtMjFkOS00ODdmLWIwMzQtNGU0YjBlYzBhZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2M5OTM5NjkwYmJkMWU2MGMwNGRlZjA5NzZjNjhkZjcxY2NiMTcxYjc0MWU1YTU0MmQ0ZjYzYWM1MGE2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PztagL2-XcO7g4-X47WLYH3MFF_zBOUORVSOCWSJ6Hw)我的 CUDA 版本是 12.3，我可以成功运行 3DGS 实时查看器。我不确定为什么这次它不起作用。谢谢！
> > > 
> > > 
> > > 嗨，我注意到您正在通过咖啡马提尼酒观看。我目前发现，对于像咖啡马提尼这样包含引导采样的场景，在您通过查看器看到场景后，查看器将与引导采样不兼容，从而抛出 cuda 内存访问错误。我们正在研究查看器。您可以选择其他场景或设置“--emsstart 30000”以禁用引导采样以通过查看器查看场景。无论如何，测试脚本都应该使用引导式采样。
> > 
> > 
> > ![1705378500597](https://private-user-images.githubusercontent.com/87744829/296930085-857dae62-d901-4652-8804-11399f6ddd79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODA4NTIsIm5iZiI6MTcwNTM4MDU1MiwicGF0aCI6Ii84Nzc0NDgyOS8yOTY5MzAwODUtODU3ZGFlNjItZDkwMS00NjUyLTg4MDQtMTEzOTlmNmRkZDc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0NDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYzIyMDc1NGM1N2Y2YjRjNmI0NTU2OGRmYzQ1MTc5ZjNlMGFiZTNlNjcwMWM4MDE0MTg3N2M4YjI4MjhiNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RR6gTbthxvvtziyJWkMTDyFMwP3S2YGXFa62-KE6yx0)
> > 我已经安装了 CUDA 工具包版本 12.3，可以使用“nvcc -V”获取结果。根据您的建议，我将尝试禁用引导采样和训练其他场景的方法。无论如何，非常感谢您的回复！
> 
> 嗨，我认为即使使用引导采样，您仍然可以在查看器中看到场景。虽然它不稳定。您是否错过了命令中的.exe？你可以试试这个
> 
> ```
> C:\xxx\bin\SIBR_gaussianViewer_app_rwdi.exe --iteration 30000 --m C:\xxx\coffee_matini
> ```

![1705381058795](https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/4c3cd202-8cbb-4524-9030-f5dadf963b6f)
<img width="340" alt="1705381138738" src="https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/7c6cb50c-4170-48dc-8fc7-81d641d47498">
![1705381420501](https://github.com/oppo-us-research/SpacetimeGaussians/assets/87744829/d196988d-0527-4f2c-b2bc-a852cfc6654b)

I used to omit the 'exe' in the 3DGS viewer, and it seems that's not the cause of the issue. I tried the other three datasets on the viewer download page, but none of them worked. Perhaps it's still a CUDA version problem？

**Comment by lizhan17** [comment]
Have you tried add ```CUDA_PATH``` in system  variables ? 
also the promt imply that you reinstall cuda, 

the Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0     works with me.

**Comment by THUSlll** [comment]
> Have you tried add `CUDA_PATH` in system variables ? also the promt implies that you reinstall cuda,
> 
> the Cuda compilation tools, release 12.3, V12.3.107 Build cuda_12.3.r12.3/compiler.33567101_0 works with me.

CUDA_HOME was set correctly before. Now, I've reinstalled CUDA, downgrading from 12.3 to 11.6, and it's working fine now. Apologies for taking up your time. Thank you for your responses! Looking forward to your future work.
