### ISSUE TITLE
Custom data / Technicolor dataset structure example

### ISSUE THREAD

**Issue by henrypearce4D** [oppo-us-research/SpacetimeGaussians#16]
Hi great work with this project!

I have request access to the Light-filed dataset. In case I am not given access, would it be possible to provide a breakdown of the folder structure and the files included?
It looks like they use image sequences rather than .mp4,  this is what we would like to test with spacetime gaussians.

**Comment by henrypearce4D** [comment]
I was given access, the undistorted dataset contains;

```
cameras_parameters.txt
# f cu cv ar sk  qw qx qy qz  tx ty tz
```
Image convention;

```
Fabien_undist_[Frame Number]_[Camera Name].png
e.g.
Fabien_undist_00001_00.png
Fabien_undist_00001_01.png
Fabien_undist_00001_02.png
Fabien_undist_00002_00.png
Fabien_undist_00002_01.png
Fabien_undist_00002_02.png
etc
```

**Comment by aleatorydialogue** [comment]
Were you able to get any custom video to work with these conventions? I'm trying to find a way to train with monocular video all day with no luck.

**Comment by henrypearce4D** [comment]
@aleatorydialogue I might be mistaken but this work is not intended with monocular video in mind.
All the examples are multi-camera.

**Comment by aleatorydialogue** [comment]
I think you are right. I had hoped I could adapt it to my own data, even if lower quality result. I'm mostly interested in usijg splatV viewer, which only seems to work with output from this project. I am trying to work on using 4dgs loader to get it to train with just one camera, but no success yet.

**Comment by lizhan17** [comment]
> I think you are right. I had hoped I could adapt it to my own data, even if lower quality result. I'm mostly interested in usijg splatV viewer, which only seems to work with output from this project. I am trying to work on using 4dgs loader to get it to train with just one camera, but no success yet.

although our method is not designed for one camera. But it can converge with the "mono" camera used in 4dgs or deformable 3dgs.  As the dataset used in these two papers are one camera that "moving" around objects. Just use the initial points used in 4dgs and replicate points into different time stamps. You can still get similar results as these two papers.  A camera moving around the object is not a mono camera, it can be seen as multi camera captured at different times.  Although I don't think in real world one can really capture dataset with one camera that can fly around objects in 2 seconds.
