### ISSUE TITLE
Some problems with the initial point cloud

### ISSUE THREAD

**Issue by moqiyinlun** [oppo-us-research/SpacetimeGaussians#20]
Since the pre_n3d.py script does not handle points3D.txt in the code, how can I get the initial point cloud for each frame to train?

**Comment by lizhan17** [comment]
you can get sparse points with the function here

from thirdparty.gaussian_splatting.helper3dg import getcolmapsinglen3d

**Comment by moqiyinlun** [comment]
Thank you very much for your answer, and then I have a small question if the code handle masked images (white background) as in the original Gaussian with the args "--white_background"? Thanks again!

**Comment by lizhan17** [comment]
In this repo along with the three dataset, we opt not to use white pixels as background.

**Comment by moqiyinlun** [comment]
Thanks! I get pretty good results!
