### ISSUE TITLE
Questions about generate videos

### ISSUE THREAD

**Issue by pange1802703882** [oppo-us-research/SpacetimeGaussians#23]
Hello, when the training is completed, how to generate some videos about any angle/pose, and save the videos

**Comment by lizhan17** [comment]
please refer to this function if you want to use moving view 

https://github.com/oppo-us-research/SpacetimeGaussians/blob/ae10a116de3e18eb99683de3dcddc4fec2558ea2/thirdparty/gaussian_splatting/scene/dataset_readers.py#L261

you can convert generated pngs to mp4 for videos.

**Comment by pange1802703882** [comment]
Thank you !!!!
