### ISSUE TITLE
Export individual frames

### ISSUE THREAD

**Issue by pablodawson** [oppo-us-research/SpacetimeGaussians#24]
Hey, thanks for your great work!

I'm trying to export individual video frames from SpacetimeGaussians to the standard 3DGS format PLY (so it can be used with the og rasterizer).
For now, I managed to export positions, rotations, and colors correctly. For example, I exported positions by applying your formula using the **pc._motion** of the current frame.
However, scales seem to be wrong. Do you handle scales in a different way to 3DGS? Using
**scales_final = pc.computedscales** seems to be wrong.

If this is a functionality you'd like to have I can PR it.

**Comment by lizhan17** [comment]
for scales without activation, you can directly call 
pc._scaling

the computed scales is after activation 
pc.computedscales = torch.exp(self._scaling)

**Comment by pablodawson** [comment]
thanks!
