### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by resurgo97** [oppo-us-research/SpacetimeGaussians#25]
Would anyone kindly provide a Dockerfile for me?
I have been struggling with setting up the environment for a few days.

---

It all starts from creating venv or installing packages taking more than 12 hours for solving environment.
So I found a workaround of using Mamba instead of Conda to make it faster, and managed to pre-process the data finally. 
However, soon I noticed that the "sparse" folder has not been generated in the colmap_0 folder for some reason.
What's worse is, at some point Mamba starts not working for some another reason, 
which made me revert to Conda and start it all over.

Then, I tried starting from a docker image which already has pytorch and everything in it, (the official pytorch image)
and I ran into "core dumped" kinda issue (which I can already find from the issues section and is yet to be solved).
As the pytorch image starts with python3.7 (rather than 3.8, as it should be), 
I tried to upgrade the python version with `conda install python=3.8`.
However, Conda said it has detected conflicts with existing packages and led to a total mass.

---

Sorry for rambling on but I will be looking forward to anyone providing a Dockerfile for this project.
Thank you for your amazing work, though.

**Comment by lizhan17** [comment]
We used an internal dockerfile. We plan to release a public dockerfile.
