### ISSUE TITLE
ModuleNotFoundError: No module named 'simple_knn'

### ISSUE THREAD

**Issue by FeFe-Orc** [oppo-us-research/SpacetimeGaussians#27]
Hi, I encountered this issue during the training phase.

(feature_splatting) C:\Users\UseName\SpacetimeGaussians>python train.py --quiet --eval --config configs/n3d_full/coffee_martini.json --model_path log/cook_martini/colmap_0 --source_path C:/Users/funique360/SpacetimeGaussians/Home/coffee_martini/colmap_0
Traceback (most recent call last):
  File "C:\Users\UseName\SpacetimeGaussians\train.py", line 42, in <module>
    from helper_train import getrenderpip, getmodel, getloss, controlgaussians, reloadhelper, trbfunction
  File "C:\Users\UseName\SpacetimeGaussians\helper_train.py", line 42, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'

pip install simple-knn
(feature_splatting) C:\Users\UseName>pip install simple-knn
Requirement already satisfied: simple-knn in c:\users\UseName\anaconda3\lib\site-packages (1.1.6)
Requirement already satisfied: numpy in c:\users\UseName\anaconda3\lib\site-packages (from simple-knn) (1.26.3)

Windows 10
CUDA 11.8

**Comment by lizhan17** [comment]
you can try ubuntu for training and testing.

what is your python version and pytorch version ? can you successfully run the following code?
import torch
print(torch.version.cuda)

**Comment by FeFe-Orc** [comment]
> you can try ubuntu for training and testing. current repo's training and testing code have some issue with windows.
> 
> what is your python version and pytorch version ? can you successfully run the following code? import torch print(torch.version.cuda)

i can't run
import torch
print(torch.version.cuda)

python : 3.11.5

pytorch                   2.1.2           py3.11_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch                     2.1.2+cu118              pypi_0    pypi
torchaudio                2.1.2+cu118              pypi_0    pypi
torchvision               0.16.2+cu118             pypi_0    pypi

**Comment by lizhan17** [comment]
i found this reply from 3dgs. i think that may help with window set up.

https://github.com/graphdeco-inria/gaussian-splatting/issues/297#issuecomment-1884974387

I still suggest you use Ubuntu(perhaps WSL) for training. as there some issues with path in the open issues.

I found this may help if you don't have a Ubuntu machine.

https://github.com/graphdeco-inria/gaussian-splatting/issues/149#issuecomment-1699160331

**Comment by lizhan17** [comment]
i found this reply from 3dgs. i think that may help with window set up.

https://github.com/graphdeco-inria/gaussian-splatting/issues/297#issuecomment-1884974387

I still suggest you use Ubuntu(perhaps WSL) for training. as there some issues with path in the open issues.

I found this may help if you don't have a Ubuntu machine.

https://github.com/graphdeco-inria/gaussian-splatting/issues/149

**Comment by lizhan17** [comment]
We have an update for WSL (Windows Subsystem for Linux) available for Windows users. If you encounter any issues with WSL, please feel free to reopen your support request.
