### ISSUE TITLE
scene initialization with 'readNerfSyntheticInfo' function

### ISSUE THREAD

**Issue by neneyork** [oppo-us-research/SpacetimeGaussians#29]
Hi Lizhan, I tried to use 'readNerfSyntheticInfo' function to read my dataset, the programme fails. Is it not finished? For I notice that this function is not listed in the intilization of Scene.

**Comment by lizhan17** [comment]
readNerfSyntheticInfo is not used. This function is original from 3dgs. We find it does not work with real world dataset from colmap.  
you can refer to 3dgs for the reason.

Our repo expect the format with colmap convention. pose convention is important.
