### ISSUE TITLE
"OSError Too many open files" on custom dataset

### ISSUE THREAD

**Issue by bnwei425** [oppo-us-research/SpacetimeGaussians#31]
Hello, thank you for the excellent work!

I try to train our custom dataset with the configuration of "techni_lite". The scene is captured by 28 cameras, and 50 frames of images and COLMAP sparse model are prepared.

I got an error in function "readColmapCamerasTechnicolor" as " OSError: [Errno 24] Too many open files: 'data/colmap_10/images/CAMP23.png' ", for line "image = Image.open(image_path)". Have you ever met a similar error as this? (I have trained the coffee_martini in Neural3D with our machine and it worked.)

**Comment by lizhan17** [comment]
Hi,
for "OS error, too many opens"
please input like "ulimit -n 4096" in terminal, then you can run the code.

**Comment by bnwei425** [comment]
Thank you for the reponse!
