### ISSUE TITLE
about Google Immersive Dataset

### ISSUE THREAD

**Issue by luoww1992** [oppo-us-research/SpacetimeGaussians#33]
i have download 02_Flames fold from Google Immersive Dataset, i want to train it likes waht in README.md.
then i have do it by script/pre_immersive_distorted.py .

so how to train it with the right cfg file ?

**Comment by lizhan17** [comment]
hi，i just uploaded the immersive part code. Please process the dataset to train.

**Comment by luoww1992** [comment]
@lizhan17 
when run new code,
error:
 ln -s data/02_Flames/camera_0002/ data/02_Flames_dist/camera_0002
done one camera
Traceback (most recent call last):
  File "script/pre_immersive_distorted.py", line 405, in <module>
    imageundistort(dstpath, offsetlist=[i for i in range(startframe,endframe)],focalscale=scale, fixfocal=None)
  File "script/pre_immersive_distorted.py", line 292, in imageundistort
    assert os.path.exists(imagepath)
AssertionError

update it ?

**Comment by lizhan17** [comment]
you can remove the data/02_Flames_dist
and rerun the code.

there shouldn't any colmap folder under the data/02_Flames/ folder .

**Comment by luoww1992** [comment]
@lizhan17 
try again, same question!

**Comment by luoww1992** [comment]
@lizhan17 
my data path likes:
![image](https://github.com/oppo-us-research/SpacetimeGaussians/assets/45957595/dc08030a-716d-4ac7-b20a-05d393fdd3ed)
only include mp4 and json

then run python script/pre_immersive_distorted.py --videopath data/02_Flames in conda colmapenv.

**Comment by lizhan17** [comment]
you can remove everything and redownlod the entire zip file, then unzip it.

colmap does not support running from vscode debugger gui. please run in command line from a terminal.

**Comment by luoww1992** [comment]
@lizhan17 
i remove the softlink func, then copy the fold to 02_Flames_dist, then run it ,
it looks no error showed, now it still is running, if it have some error, i will ask you

**Comment by luoww1992** [comment]
@lizhan17 

train finished with no info shows:
i have finished dataset pred, 
when i run cmd:
python train_imdist.py --quiet --eval --config configs/im_distort_full/02_Flames.json --model_path log/02_Flames/colmap_0 --source_path data/02_Flames_dist/colmap_0

it is finish after some times,  after begin training,  i notice that it costs many RAM , so i use 64G RAM and 48G GPU, 
but the same question.

**Comment by lizhan17** [comment]
but the same question.

can you print the error log, i can't know the details of the error ?

**Comment by luoww1992** [comment]
@lizhan17 ,
cmd: python train_imdist.py --quiet --eval --config configs/im_distort_lite/02_Flames.json --model_path log/02_Flames/colmap_0 --source_path data/02_Flames_dist/colmap_0

this is no useful print info show !
only print this when run this code: print("Optimizing " + args.model_path)

**Comment by lizhan17** [comment]
for debugging, you can remove ```--quiet```

**Comment by luoww1992** [comment]
@lizhan17 
log:
==========================
Optimizing log/02_Flames/colmap_0
overload config from configs/im_distort_lite/02_Flames.json [08/04 11:59:21]
failed set config: test_iteration [08/04 11:59:21]
finish load config from configs/im_distort_lite/02_Flames.json [08/04 11:59:21]
render option train_ours_litess [08/04 11:59:21]
Output folder: log/02_Flames/colmap_0 [08/04 11:59:21]
Tensorboard not available: not logging progress [08/04 11:59:21]
use model ours_lite [08/04 11:59:21]
Reading camera 45/45 [08/04 11:59:22]
Loading Training Cameras [08/04 11:59:22]
read one [08/04 11:59:23]
id 0 [08/04 11:59:24]
read one [08/04 11:59:24]
......
id 48 [08/04 12:04:36]
read one [08/04 12:04:36]
id 49 [08/04 12:04:36]
Number of points at initialisation :  311985 [08/04 12:04:37]
move decoder to cuda [08/04 12:04:40]
Training progress:   0%|                                                                                                                                                                                 | 0/20000 [00:00<?, ?it/s]p
lease copy pick view [08/04 12:04:41]
Training progress:   0%|                                                                                                                                                                                 | 0/20000 [00:01<?, ?it/s]
================================
how to do ?

**Comment by lizhan17** [comment]
got it. you need to copy the config file we provide to the data set folder.
please see the step3 of google immersive dataset 
```Copy the picked views files to the scene dir....```

**Comment by luoww1992** [comment]
@lizhan17 
it is running, while what is the pkl file ? how to make it ?

**Comment by lizhan17** [comment]
pkl file is generated by inferencing our full model initialized with ```duration=1```. 
i provide the way to dump it in the commented code. We finalize and fix the pickle file in the early experiments. The selected views should not be very different as the the model doesn't change a lot and the model is not trained.

**Comment by luoww1992** [comment]
@lizhan17 
i am try to make a  new dataset from project 4K4D in Github,
i find that the fx and fy,
what is the args meaning about focal_length in json ? 
is it (fx+fy)/2 or (fx**2+fy**2)**0.5 ?

**Comment by luoww1992** [comment]
@lizhan17 
i try use  (fx2+fy2)**0.5 
but error show:
RuntimeError: amax(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument

**Comment by lizhan17** [comment]
fx and fy handle the position of center in our code. it may has different meaning under different code repo. I don't know the details of 4k4d. 

https://ksimek.github.io/2013/06/03/calibrated_cameras_in_opengl/
https://stackoverflow.com/a/22064917

**Comment by luoww1992** [comment]
@lizhan17 
the fx ,fy are from the camera intri

**Comment by lizhan17** [comment]
if the fx ,fy are from the camera intri, i think fx and fy are focal length of x and y.
it should be ```focal_length_x``` and ```focal_length_y``` in our loader code. 
please also consider intr.params[2] as fx and update the cxr by fx and cyr by fy
        ```
            cxr =   ((intr.params[2] )/  width - 0.5) 
            cyr =   ((intr.params[3] ) / height - 0.5) 
        ```

specially for the error (cause by scene with many empty backgrounds):
RuntimeError: amax(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument

i guess for this error you can simply modify this. also this will not provide an accurate depth guideance for ems
```
validdepthdict[viewpoint_cam.image_name] = 15 #torch.median(depth[slectemask]).item()  
depthdict[viewpoint_cam.image_name] = 15 #torch.amax(depth[slectemask]).item() 
```

**Comment by remmel** [comment]
> @lizhan17 when run new code, error: ln -s data/02_Flames/camera_0002/ data/02_Flames_dist/camera_0002 done one camera Traceback (most recent call last): File "script/pre_immersive_distorted.py", line 405, in imageundistort(dstpath, offsetlist=[i for i in range(startframe,endframe)],focalscale=scale, fixfocal=None) File "script/pre_immersive_distorted.py", line 292, in imageundistort assert os.path.exists(imagepath) AssertionError
> 
> update it ?

That error occured because you use relative path (to the project dir), and because when creating a symbolic link with `ln -s` if the DIRECTORY is relative it must be relative to the TARGET.
In short: use absolute path (or use pathlib and .resolve() in the code )
