### ISSUE TITLE
How to get focal_scale in script/pre_immersive_distorted.py

### ISSUE THREAD

**Issue by LuckyOne09** [oppo-us-research/SpacetimeGaussians#36]
Hello! Firstly, thank you for your contributions and for sharing your work with the community. I've been exploring the script `pre_immersive_distorted.py` and came across the parameter `focal_scale` being hardcoded within the `immmersivescaledict`. While experimenting with fisheye data in the immersive dataset, I'd like to understand how to dynamically obtain this scale parameter.

Could you please provide guidance on how to  calculate the `focal_scale ` value? This would greatly assist me in processing additional fisheye data independently and utilizing your excellent STGS for further experimentation.

Looking forward to your response and eager to explore the results!

Thank you once again for your efforts.

**Comment by LuckyOne09** [comment]
Thank you for your quick reply! it is very helpful. but I found another question regarding the undistorted image. I noticed that the edges of the undistorted image are significantly stretched. I'm concerned about whether this affects the overall quality of the results.
![img_v3_029j_7731b803-5256-4fb9-b78a-c16acff9071g](https://github.com/oppo-us-research/SpacetimeGaussians/assets/38714962/4d4715aa-900f-418a-bcf4-ee9437cf110f)
![img_v3_029j_3f589bd2-4898-4540-8714-bfd48950bc4g](https://github.com/oppo-us-research/SpacetimeGaussians/assets/38714962/1104e266-eb6d-4f61-a5b1-089f295c73ae)

**Comment by lizhan17** [comment]
Your undistorted images look like what we have.  it may have bad effects. 
This undistorted image is just for structure from motion points.

our model's ground truth image for training is still the **distorted** image in this mode. We will apply a distortion grid flow to the rendered image in the render pipeline. Although there will be some inevitable resampling error by the grid sampling.

**Comment by LuckyOne09** [comment]
I get it! Thank you for your guidance!
