### ISSUE TITLE
Building the new Viewer?

### ISSUE THREAD

**Issue by MikeJPelton** [oppo-us-research/SpacetimeGaussians#37]
Hi - thank you for letting us know the code for your SIBR viewer modifications has been released! I am trying to understand the instructions for building the viewer from the new code. After I clone sibr_core:
```git clone https://gitlab.inria.fr/sibr/sibr_core.git```
...and run Cmake, there's no CudaRasterizer folder under 'SpacetimeGaussians\thirdparty\sibr_core\extlibs' to copy your code into? I wonder if I am I misunderstanding your instruction:
```# Just, update everthing except .git in `extlibs\CudaRasterizer` with our `thirdparty\gaussian_splatting\realtimedemo\extlibs\CudaRasterizer' ```
All guidance welcome!

**Comment by lizhan17** [comment]
Ok. first
```git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive```
```cd gaussian-splatting```
```cd SIBR_viewers```
```cmake -Bbuild .```

replace the 3dgs viewer's code with our code.  in thirdparty\gaussian_splatting\realtimedemolite

**Comment by MikeJPelton** [comment]
Thank you for your extremely prompt clarification - that's very helpful indeed!
