### ISSUE TITLE
how to render show when training?

### ISSUE THREAD

**Issue by luoww1992** [oppo-us-research/SpacetimeGaussians#38]
i see we need to render the result after training,
so Can we rendering the point cloud when the model is training?
and In this way, as the model continues to be trained, we can see the continuous optimization of the rendering results。

**Comment by lizhan17** [comment]
You cannot see results during rendering. You can modify the guided sampling codes to export training views during training. Or add back 3dg"s code of remote viewer, which needs more efforts, our code is refactored.

**Comment by luoww1992** [comment]
@lizhan17 
Can you share some datasets that surround objects in 360 degrees?

**Comment by lizhan17** [comment]
d-nerf／ hypernerf datast seems to meet your requirement. 
support for a d-nerf dataset can be a future work. (they are mono-camera datasets).

**Comment by luoww1992** [comment]
@lizhan17 
i have seed these, but it is one cam video picture.
some other dataset ?

**Comment by lizhan17** [comment]
perhaps hypernerf ? or some datasets in human avatar papers? I am not very farmiliar with these datasets.
