### ISSUE TITLE
What's the difference between gaussian_rasterization_ch9 and gaussian_rasterization_ch3?

### ISSUE THREAD

**Issue by Gatswei** [oppo-us-research/SpacetimeGaussians#39]
Excellent work. And I have a question. 
What's the difference between gaussian_rasterization_ch9 and gaussian_rasterization_ch3?

**Comment by lizhan17** [comment]
gaussian_rasterization_ch9 is for training our full model. 
gaussian_rasterization_ch3 is for training our lite model
