### ISSUE TITLE
Issue during preprocessing of Neural 3D Video dataset

### ISSUE THREAD

**Issue by jayaramreddy10** [oppo-us-research/SpacetimeGaussians#4]
Hi, thanks for making the code public. I am getting below issue when running the preprocessing code on Neural 3D dataset (cook_spinach). Any idea what might be the issue here?

Command: python script/pre_n3d.py --videopath ../neural_3d_video_dataset/cook_spinach/ 
**Error message: 

Undistorted image found; copying to location: ../neural_3d_video_dataset/cook_spinach/colmap_0/images/cam13.png
PC: @     0x7ff558e6f00b gsignal
*** SIGABRT (@0x71b6b838003180d5) received by PID 3244245 (TID 0x7ff53f5ff000) from PID 3244245; stack trace: ***
    @     0x7ff580de7631 (unknown)
    @     0x7ff577939420 (unknown)
    @     0x7ff558e6f00b gsignal
    @     0x7ff558e4e859 abort
    @     0x7ff5590bc8d1 (unknown)
    @     0x7ff5590c837c (unknown)
    @     0x7ff5590c83e7 std::terminate()
    @     0x7ff5590c836f std::rethrow_exception()
    @     0x55cfc263b79a colmap::COLMAPUndistorter::Run()
    @     0x55cfc2808291 colmap::Thread::RunFunc()
    @     0x7ff5590f4df4 (unknown)
    @     0x7ff57792d609 start_thread
    @     0x7ff558f4b133 clone
Aborted (core dumped)**

Thanks

**Comment by lizhan17** [comment]
Hi, It seesm to me that colmap failed. We can first check that colmap is installed under the python=3.8 environment by conda channel ?

**Comment by jayaramreddy10** [comment]
Yes, I have installed the conda env as per instructions . Its 3.8 .

(colmapenv) jayaram.reddy@super:~$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by lizhan17** [comment]
> Yes, I have installed the conda env as per instructions . Its 3.8 .
> 
> 
> 
> (colmapenv) jayaram.reddy@super:~$ python
> 
> Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
> 
> [GCC 11.2.0] :: Anaconda, Inc. on linux
> 
> Type "help", "copyright", "credits" or "license" for more information.

Hi, for the input to the script, is this "../Neural3D/cook_spinach/" a relative path?

**Comment by jayaramreddy10** [comment]
I have given absolute path only, not the relative, didnt paste it here as it was very long.

**Comment by lizhan17** [comment]
Hi, i notice that the path for colmap error is neural_3d_video_dataset/cook_spinach/colmap_0/images/cam13.png    While our codebase expect the processed colmap data at the same dir. Could you check that ? Thanks.  
<location>
|---cook_spinach
|   |---colmap_<0>
|   |---colmap_<...>
|   |---colmap_<299>

**Comment by lizhan17** [comment]
> I have given absolute path only, not the relative, didnt paste it here as it was very long. Won't it work with absolute path?

It should work with absolute path. (Code is designed for absolute path.) could you mind sending me a zoom link that I can see the error  and the data processed. My email is in the paper.

**Comment by jayaramreddy10** [comment]
Yes, it was able to run the Gaussian splatting repo colmap script. Below are the details:

System: 
Distributor ID: Pop
Description:    Pop!_OS 20.04 LTS
Release:        20.04
Codename:       focal

Machine: 
![Screenshot from 2024-01-01 13-52-59](https://github.com/oppo-us-research/SpacetimeGaussians/assets/111297422/19da89d5-a463-40b4-bee1-4cf15fd3c598)

I am using the GPU id 1 from the server to run the script .. 

Let me know if you need any other details. Thanks

**Comment by lizhan17** [comment]
> Yes, it was able to run the Gaussian splatting repo colmap script. Below are the details:
> 
> 
> 
> System: 
> 
> Distributor ID: Pop
> 
> Description:    Pop!_OS 20.04 LTS
> 
> Release:        20.04
> 
> Codename:       focal
> 
> 
> 
> Machine: 
> 
> ![Screenshot from 2024-01-01 13-52-59](https://github.com/oppo-us-research/SpacetimeGaussians/assets/111297422/19da89d5-a463-40b4-bee1-4cf15fd3c598)
> 
> 
> 
> I am using the GPU id 1 (rtx3060) from the server to run the pre_n3d.py script .. . I have also tried on GTX TITAN X in the same server, its giving the same issue.
> 
> 
> 
> Let me know if you need any other details. Thanks

Hi, I am out for two days. I will check this on my machine with similar setting as yours two days later. If you have time before my test, you can look for issues in colmap GitHub.

**Comment by jayaramreddy10** [comment]
> > Yes, it was able to run the Gaussian splatting repo colmap script. Below are the details:
> > System:
> > Distributor ID: Pop
> > Description:    Pop!_OS 20.04 LTS
> > Release:        20.04
> > Codename:       focal
> > Machine:
> > ![Screenshot from 2024-01-01 13-52-59](https://private-user-images.githubusercontent.com/111297422/293576022-19da89d5-a463-40b4-bee1-4cf15fd3c598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTU4NDYsIm5iZiI6MTcwNDExNTU0NiwicGF0aCI6Ii8xMTEyOTc0MjIvMjkzNTc2MDIyLTE5ZGE4OWQ1LWE0NjMtNDBiNC1iZWUxLTRjZjE1ZmQzYzU5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMzI1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjUxMGU2MGY3YmExODkxMzkwMGM1ZDIwNzVmZGVmNjFmZWJjOGEzYTAxZTZhZjU3Mjc4ZjgwYTBiZjIxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ePcsXw2xge_s8J0yBJYjullFJaLbriOWAs8y1pRIZ6Y)
> > I am using the GPU id 1 (rtx3060) from the server to run the pre_n3d.py script .. . I have also tried on GTX TITAN X in the same server, its giving the same issue.
> > Let me know if you need any other details. Thanks
> 
> Hi, I am out for two days. I will check this on my machine at home with similar setting as yours two days later.

To be precise , error is happening here and code is exiting there. 

    img_undist_cmd = "colmap" + " image_undistorter --image_path " + inputimagefolder + " --input_path " + distortedmodel  + " --output_path " + folder  \
    + " --output_type COLMAP" 
    exit_code = os.system(img_undist_cmd)

**Comment by lizhan17** [comment]
Hi, do you have a precious crash before this step? Is the output folder empty before the function is called?

**Comment by jayaramreddy10** [comment]
Got it, will do the above. Thanks for the help. You can close the issue ...
