### ISSUE TITLE
How to test on Google Immersive Dataset with distortion camera model ?

### ISSUE THREAD

**Issue by DapengFeng** [oppo-us-research/SpacetimeGaussians#40]
I have observed the item listed in the readme, however, it lacks detailed instructions.

https://github.com/oppo-us-research/SpacetimeGaussians/blob/dda2e6e591ee1c03ba3754f389a8e27af508c812/README.md?plain=1#L207-L208

**Comment by lizhan17** [comment]
we provide testing code here already 
![image](https://github.com/oppo-us-research/SpacetimeGaussians/assets/32379931/0d57dcb1-831a-405c-9567-7105bdacb7db)

**Comment by DapengFeng** [comment]
Thank you. It resolved my confusion.
