### ISSUE TITLE
TRBF output

### ISSUE THREAD

**Issue by Hansello218** [oppo-us-research/SpacetimeGaussians#41]
When using radial basis functions to represent opacity, I noticed that the computation method provided in your code does not match the calculation method given in the equation 7 of the paper. Could you please clarify this?
![1](https://github.com/oppo-us-research/SpacetimeGaussians/assets/112995477/229651a5-d146-424e-a227-52841f0f056e)

**Comment by lizhan17** [comment]
it is a parametric trick (logrithim of s), now trbfoutput is in range (0 to1) to make sure final opacity range is (0 to1). 

if you take the rbf function ```return torch.exp(-1*x.pow(2))```, you can get
```torch.exp(-1*(offset / exp(trbfscale)).pow(2))```, same as  
```torch.exp(-1*(offset * exp(-trbfscale)).pow(2))```, where
```-1*(offset * exp(-trbfscale)).pow(2)``` is same with ```-1*offset.pow(2)* exp(-trbfscale).pow(2)```,
is same with
```-1* exp(-trbfscale).pow(2)*offset.pow(2)```
```-1* exp(-2trbfscale)*offset.pow(2)```

![image](https://github.com/oppo-us-research/SpacetimeGaussians/assets/32379931/6de2d85c-132c-4ec5-a756-7c9d16fe79fe)

**Comment by Hansello218** [comment]
It's correct.Thanks a lot!
