### ISSUE TITLE
How does the gaussian_rasterization_ch9 change compared to the original rasterization？

### ISSUE THREAD

**Issue by Gatswei** [oppo-us-research/SpacetimeGaussians#49]
Hello，I have a question.
How does the gaussian_rasterization_ch9 change compared to the original rasterization？Just change NUM_CHANNELS?
Look forward to your reply，Thank you.

**Comment by lizhan17** [comment]
Hi the code is from ```https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth``` with modifcaiton of Just changing NUM_CHANNELS
