### ISSUE TITLE
A little question about the function "test_ours_lite"

### ISSUE THREAD

**Issue by zachzhang07** [oppo-us-research/SpacetimeGaussians#51]
Thanks for your excellent work!
I have a question about the function "test_ours_lite" in thirdparty/gaussian_splatting/renderer/__init__.py. It looks like the method of obtaining postion of gaussians (**means3d**) in "test_ours_lite" is different from that in "train_ours_lite". May I ask why there is this difference.

**Comment by lizhan17** [comment]
Hi, 
train_ours_lite is for training, while test_ours_lite is for fast inference. 
test_ours_lite's postion in fused in the cuda code. (see the prepreprocess function in forward.cu )

**Comment by zachzhang07** [comment]
Understood. Thank you for your reply!
