### ISSUE TITLE
Documentation for the `densify` Training Parameter

### ISSUE THREAD

**Issue by NeilNie** [oppo-us-research/SpacetimeGaussians#57]
Hi there,

Thanks for open-sourcing this great project. I am wondering if you can provide some documentation for the parameter `densify` used and defined in the `train.py` and `train_imdist.py` script. 

In the provided config files, the parameter is set to various values, such as 1, 3, 8, etc. I see that 1 means `n3d` dataset. But can you please explain what 8, 7, 6 mean? thank you!

**Comment by lizhan17** [comment]
8, 7, 6 are for immersive dataset. experimentally setted for the scenes in google immersive dataset.  8 removes minmax points. 6 pruning points until 9000 iterations. 7 pruning points until the end of densification.   


(key point is ```densify_prunecloneimgeneral``` in ```6-8``` is slightly different from ```1-3``` . In neural3d and technicolor ```1-3```, whitebalance is stable among different cameras, so we can densify points to random time.  While in ```densify_prunecloneimgeneral```, we uncomment this line  https://github.com/oppo-us-research/SpacetimeGaussians/blob/31bf5f27bc60396fc406d44f43905c63dc626496/thirdparty/gaussian_splatting/scene/oursfull.py#L1073C1-L1074C1 

you can see sand/rock presents different color in different cameras in the scene ```14_puppy``` raw videos. Our example on the website (a dog walk on the sands ```14_puppy```) also show the color difference of rock, as the training camera present different colors for the rock.  

3 is for technicolor dataset, which is more general.

**Comment by NeilNie** [comment]
Thank you for the information!
