### ISSUE TITLE
Question about custom video

### ISSUE THREAD

**Issue by guanjunwu** [oppo-us-research/SpacetimeGaussians#6]
Hi, Thanks for your great work!
Can you guide training with custom monocular video? Such as input like `nerfstudio`'s preprocessing pipeline.
Meanwhile, I would also like to ask whether you test your model in the monocular dataset like `hypernerf`?

**Comment by lizhan17** [comment]
> Hi, Thanks for your great work!
> 
> Can you guide training with custom monocular video? Such as input like `nerfstudio`'s preprocessing pipeline.
> 
> Meanwhile, I would also like to ask whether you test your model in the monocular dataset like `hypernerf`?

Thank you for your question. Our paper focuses on multi-cam settings. Our codebase currently cannot process / train on the mono camera settings. For a new dataset, we need to check the pose conventions. We would consider test on the mono cameras dataset in the near future.

**Comment by aleatorydialogue** [comment]
Any update on monocular video datasets being trained successfully? I'm very interested in working on this for my own video. I expect quality will suffer compared with larger datasets but is there any technical reason it won't be able to converge?

**Comment by lizhan17** [comment]
it can converge with the loader of 4dgs code (PSNR of Broom is is 21.7). We are working on the mono camera setting, it can be seen as a future work.

**Comment by aleatorydialogue** [comment]
Do you mean using 4dgs loader within your project? Or you just mean 4dgs is able to process monocular video? I have been successful with that repo but there isn't a good browser video for that ply output yet

**Comment by lizhan17** [comment]
4dgs loader with some modifciations. our method is using spacetime points (points with time) to init.
