### ISSUE TITLE
Reconstructions from Paper

### ISSUE THREAD

**Issue by KeKsBoTer** [oppo-us-research/SpacetimeGaussians#60]
Hello,

thanks for the amazing work!
Do you plan on releasing more reconstructions? 
It would be good to have the reconstructions (light and "normal" model) as baseline for comparisons.
I have seen that you published two reconstructions together with the viewer. 

Best
Simon

**Comment by lizhan17** [comment]
Thank you for you interesting. We have no plan for more models. You can use current code for comparisons.
