### ISSUE TITLE
maskgt parameter missing from train.py

### ISSUE THREAD

**Issue by remmel** [oppo-us-research/SpacetimeGaussians#68]
Hello,

In the README, you indicated to use the `maskgt` parameter as below, however `train.py` does not handler that parameter.
`train.py: error: unrecognized arguments: --maskgt 1`

https://github.com/oppo-us-research/SpacetimeGaussians/blob/31bf5f27bc60396fc406d44f43905c63dc626496/README.md?plain=1#L196-L200

https://github.com/oppo-us-research/SpacetimeGaussians/blob/31bf5f27bc60396fc406d44f43905c63dc626496/thirdparty/gaussian_splatting/helper3dg.py#L32-L53

Regards,

**Comment by lizhan17** [comment]
Hi, for train.py we don't need maskgt,  maskgt is used for training immersive video in train_imdist.py

the training label images will contain black borders, so we need a mask. that is a special case.

**Comment by lizhan17** [comment]
maskgt parameter is setting in 


https://github.com/oppo-us-research/SpacetimeGaussians/blob/401ecf1fd9d764568302f0fd489d82d4554827e7/thirdparty/gaussian_splatting/arguments/__init__.py#L146
