### ISSUE TITLE
Query regarding dataset without ground truth poses

### ISSUE THREAD

**Issue by jayaramreddy10** [oppo-us-research/SpacetimeGaussians#7]
Hi, a quick question regarding the limitations 

In preprocessing step i.e pre_n3d.py script, it expects ground truth poses (poses_bounds.npy) in convertdynerftocolmapdb function to generate folders <colmap_0>....<colmap_299> for Neural3DVideo dataset. Does the method handle datasets which don't have any ground truth extrinsics and intrinsics , basically just the videos from multiple viewpoints? 

If it can handle those datasets, could you please suggest the changes required in the script? 

Thanks

**Comment by lizhan17** [comment]
Hi,you can use software like colmap to estimate the poses of videos if you don't have ground truth poses. (We recommend that use Colmap conventions for poses.) We recommend you use the technicolor dataset loader for real world data, as images are uncentered. Also this codebase cannot process/ train on the mono camera videos. We will consider test on the mono camera setting in the near future.

**Comment by jayaramreddy10** [comment]
Ok, to be sure, you suggest to run colmap sparse model on images from all cameras at every timestep/offset?

**Comment by lizhan17** [comment]
> Ok, to be sure, you suggest to run colmap sparse model on images from all cameras at every timestep/offset?

I suggest that you can get poses from a single time stamp then use that estimated poses to get points for the rest time stamp.  In such way, they can share the same world mapping at different time.

**Comment by jayaramreddy10** [comment]
> > Ok, to be sure, you suggest to run colmap sparse model on images from all cameras at every timestep/offset?
> 
> I suggest that you can get poses from a single time stamp then use that estimated poses to get points for the rest time stamp. In such way, they can share the same world mapping at different time.

Agree but could you please elaborate this (use that estimated poses to get points for the rest time stamp) and how do we go about that?

**Comment by lizhan17** [comment]
treat colmap_0's  extrinsics and intrinsics as ground truth  extrinsics and intrinsics. then use that ground truth  extrinsics and intrinsics for the rest times.
