### ISSUE TITLE
Best config for im_undistort_lite/02_Flames.json

### ISSUE THREAD

**Issue by remmel** [oppo-us-research/SpacetimeGaussians#70]
Hello Li,

I want to reproduce the _02_Flames_ (Google Immersive dataset).

I ran 02_Flames_undist will following almost default params:

im_undistort_lite/02_Flames.json:

```json
{
  "resolution": 2,
  "model": "ours_lite",
  "scaling_lr": 0.001,
  "trbfslinit": 4.0,
  "preprocesspoints": 3,
  "test_iteration": 25000,
  "densify": 3,
  "emsstart": 30000,
  "desicnt": 6,
  "duration": 5, #changed from 50 to 5 to fit my 12GB VRAM
  "rgbfunction": "None",
  "loader": "technicolor",
  "rdpip": "train_ours_lite"
}
```

```shell
python train.py --gtmask 1 --config configs/im_undistort_lite/02_Flames.json --model_path log/02_Flames_undist/01 --source_path ../dataset/immersive/02_Flames_undist/colmap_0
```

I get low quality result as seen on the screenshot:
![image](https://github.com/user-attachments/assets/433f94cb-4807-4567-9ec0-c9987d71f476)

However after playing with the parameters, I get better result, specifically after removing the _trbfslinit_ :
![image](https://github.com/user-attachments/assets/a054f6aa-8eec-4e8c-9a93-c666413dabfc)

Logs are here: [GDrive](https://drive.google.com/drive/folders/1Oidn1Pu9y_nEo8HE476p2ZU3IAP1sTM7?usp=sharing) - log `01-dur5` and then `01-dur5-res4-notrbfslinit`

However result are not good enough, specifically comparing with _02_flames_ from https://antimatter15.com/splaTV/ or _flame_steak_ using n3d_lite/flame_steak.json My guess is that there are not enough splats.

Thus, what is the best configuration you found for _im_undistort_lite/02_Flames.json_ ? You paper is using _im_distort[lite|full]_ isn't it? _im_undistort_  should reach same quality than _im_distort_ ? Why did not you tried to go further with _im_undistort_ version?

I know that I'm not using full resolution, but it should be way enough comparing with my n3d tries.

<details>
  <summary>[edit] train_imdist.py lite comparison</summary>

as comparison, this is the result obtained using _train_imdist.py lite_, with _resolution:4_ and _duration:5_ (but something strange seems to occurs with the time) :
![image](https://github.com/user-attachments/assets/38bcd484-93c8-42e2-b516-61f60b216e83)

```
python train_imdist.py --config configs/im_distort_lite/02_Flames.json --model_path log/02_Flames_dist/01-lite-dur5 --source_path ../dataset/immersive/02_Flames_dist/colmap_0
```
see log _02_Flames_dist/01-lite-dur5-res4/_
commenting https://github.com/oppo-us-research/SpacetimeGaussians/blob/7eba660bc8766528c18b87f8b4194d142de9b137/thirdparty/gaussian_splatting/utils/camera_utils.py#L121 and https://github.com/oppo-us-research/SpacetimeGaussians/blob/7eba660bc8766528c18b87f8b4194d142de9b137/thirdparty/gaussian_splatting/utils/camera_utils.py#L141
</details>

Thanks for your help!

**Comment by lizhan17** [comment]
1) for the im_undistort_lite config:
we need 50 frames to make points from 50 frames can cover each other for some static points. you can think it is a video codec with 50 frames. it can be much better than the 5 frames model. 

if you use **5 frames**, the default trbfinit (which increase the range of each frame can cover in time compared to  4) can also increase the quality as each frame can cover more timestamps. 

for the demo model on the website, we use all the cameras to train with 50 frames. 

2)  for the train_imdist config:

for immersive models that are used to report results in the paper, the we are using camera super sampling (camss) to render at x2 resolution (to compensate the fisheye warping error). As other methods are trained with half resolution ground truth images, so i force the code to **render** at original resolution and use half resolution image as ground truth label.

**Comment by remmel** [comment]
Thanks, I'll try on then on a bigger VRAM machine with the 50 frames thus, I reopen if needed
