### ISSUE TITLE
Render the full model

### ISSUE THREAD

**Issue by Tziming** [oppo-us-research/SpacetimeGaussians#80]
Hi, following the steps of the tutorial, I managed to reproduce the work in the article, except for rendering the full model. When I render the full model via SIBR, it prompts an error for CUDA. Device is a single RTX3090(24G), I can train a lite model and a full model. And I can render the lite model, but not the full model. The trained data is Neural 3D Dataset. The error depicted as follow:

```
[SIBR] ##  ERROR  ##:   FILE /home/user/OpensourceDEMO/faster3dgstream/SpacetimeGaussians/thirdparty/gaussian-splatting/SIBR_viewers/src/projects/gaussianviewer/renderer/GaussianView.cpp
                        LINE 694, FUNC onRenderIBR
                        A CUDA error occurred during rendering:an illegal memory access was encountered. Please rerun in Debug to find the exact line!terminate called after throwing an instance of 'std::runtime_error'
  what():  See log for message errors
```

I'm guessing that my device doesn't render full models, which may be related to the configuration of GPU memory, architecture, rasterization, etc., and I monitored the usage of video memory during the render loading process, and there was no GPU memory overflow. So, how do I modify the code if I want the full model to be rendered on my current device ? Thank you so much！

**Comment by lizhan17** [comment]
Hi, 
the provided SIBR code not support full model.

**Comment by Tziming** [comment]
Thanks! I understand. The updated two default folders is code about lite model. If I want SIBR to support full model, it seems like I need to modify both parts of the code, and recompile SIBR.

**Comment by lizhan17** [comment]
yes.
