### ISSUE TITLE
what is network_output in loss_utils.py

### ISSUE THREAD

**Issue by JUNEeer** [oppo-us-research/SpacetimeGaussians#83]
when i use Li1=L1_loss,error happens.ValueError: Network output is None!

**Comment by JUNEeer** [comment]
此网络训练时候用到的networks.py主要用到了哪几层

**Comment by lizhan17** [comment]
you mean only use l1 loss ? which option of op.reg is ?

**Comment by JUNEeer** [comment]
![image](https://github.com/user-attachments/assets/18feed42-2fb1-4a6f-ae84-fa536f1cf09e)
render_pkg = render(viewpoint_cam, gaussians, pipe, background,  override_color=None,  basicfunction=rbfbasefunction, GRsetting=GRsetting, GRzer=GRzer)，in this code，render_pkg's output is None,how can i fix it or how to find what is the meaning of render_pkg

**Comment by JUNEeer** [comment]
> you mean only use l1 loss ? which option of op.reg is ?

![image](https://github.com/user-attachments/assets/3f1c2acb-9e2c-4baf-83c7-1cfabf979734)
in loss_utils.py,the question happens

**Comment by JUNEeer** [comment]
During my debugging，Why when your main program starts running, the output of network.py is output first, and then the Optimizing model. . .，It's a very strange phenomenon，What's the logic here

**Comment by lizhan17** [comment]
the image cropped seems to be different from our code. 

in training.py we run two seperate loops. 

first loop is before actually training, just to get some metrics like depth etc to guide following training loops. 

second training loop is normal training like 3DGS, with batch cached gradients for training.

**Comment by JUNEeer** [comment]
![image](https://github.com/user-attachments/assets/a0bf17d3-65e7-4b5f-b5b1-5f3945aa742f)
in line 179

**Comment by JUNEeer** [comment]
> 裁剪的图像似乎与我们的代码不同。
> 
> 在 training.py 中我们运行两个单独的循环。

> 第一次循环是在实际训练之前，只是为了获得一些指标（例如深度等）来指导接下来的训练循环。
> 
> 第二个训练循环是类似 3DGS 的正常训练，使用批量缓存梯度进行训练。

两次训练的接口分别在哪里

**Comment by JUNEeer** [comment]
> the image cropped seems to be different from our code.
> 
> in training.py we run two seperate loops.
> 
> first loop is before actually training, just to get some metrics like depth etc to guide following training loops.
> 
> second training loop is normal training like 3DGS, with batch cached gradients for training.
Hello, can you tell me where the interfaces for the two trainings are?

**Comment by lizhan17** [comment]
that should follow 3dgs style.  first render, then compute gradients, then get weight updated. 

https://github.com/graphdeco-inria/gaussian-splatting/blob/54c035f7834b564019656c3e3fcc3646292f727d/train.py#L111C1-L114C1

**Comment by lizhan17** [comment]
first loop without gradients. 
https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/train.py#L130


second loops iterations, 
       each iterations
              we sample some views from a random time.
                  for each view sampled
                       compute and cache gradients 
            
https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/train.py#L159

sorry, it is a bit lengthy.

**Comment by JUNEeer** [comment]
![image](https://github.com/user-attachments/assets/9c89d388-6a69-4ff7-afd4-abb750f5f0d0)
When I debug it myself, the output of render_pkg is displayed as None, so where does render_pkg get the information

**Comment by JUNEeer** [comment]
Another problem is that when I add output to networks.py, its output is before this
![image](https://github.com/user-attachments/assets/a0dfe680-010a-4066-99e6-55572c5d1ebe)
![image](https://github.com/user-attachments/assets/276b378b-42a2-4e7b-8696-dbb16066a6c3)

**Comment by JUNEeer** [comment]
> we have a helper function first get render functions from
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_train.py#L50
> 
> the different render functions in here https://github.com/oppo-us-research/SpacetimeGaussians/blob/main/thirdparty/gaussian_splatting/renderer/__init__.py
> 
> each function should return a package,
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/thirdparty/gaussian_splatting/renderer/__init__.py#L105
Thank you for your attentive reply！

**Comment by JUNEeer** [comment]
> we have a helper function first get render functions from
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_train.py#L50
> 
> the different render functions in here https://github.com/oppo-us-research/SpacetimeGaussians/blob/main/thirdparty/gaussian_splatting/renderer/__init__.py
> 
> each function should return a package,
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/thirdparty/gaussian_splatting/renderer/__init__.py#L105

Obviously the return value is different from the value in render_pkg, causing render_pkg to have no value
![image](https://github.com/user-attachments/assets/8b94e792-5a72-489f-bed7-225a068dbc9e)
![image](https://github.com/user-attachments/assets/fbd004ad-9c9f-4a54-b5cf-016f04ae62c9)

**Comment by JUNEeer** [comment]
> we have a helper function first get render functions from
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_train.py#L50
> 
> the different render functions in here https://github.com/oppo-us-research/SpacetimeGaussians/blob/main/thirdparty/gaussian_splatting/renderer/__init__.py
> 
> each function should return a package,
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/thirdparty/gaussian_splatting/renderer/__init__.py#L105

![image](https://github.com/user-attachments/assets/0d51fd8b-a57f-4155-a68b-523fb86f8b72)

**Comment by JUNEeer** [comment]
> > we have a helper function first get render functions from
> > https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_train.py#L50
> > 
> > the different render functions in here https://github.com/oppo-us-research/SpacetimeGaussians/blob/main/thirdparty/gaussian_splatting/renderer/__init__.py
> > each function should return a package,
> > https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/thirdparty/gaussian_splatting/renderer/__init__.py#L105
During the first loop iteration, the getrenderparts function was not used and the render_pkg was called directly.
Obviously render_pkg is not returned

**Comment by JUNEeer** [comment]
> we have a helper function first get render functions from
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_train.py#L50
> 
> the different render functions in here https://github.com/oppo-us-research/SpacetimeGaussians/blob/main/thirdparty/gaussian_splatting/renderer/__init__.py
> 
> each function should return a package,
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/thirdparty/gaussian_splatting/renderer/__init__.py#L105

During the first loop iteration, the getrenderparts function was not used and the render_pkg was called directly.
Obviously render_pkg is not returned

**Comment by JUNEeer** [comment]
![image](https://github.com/user-attachments/assets/ee12addf-b679-46a3-aa49-c6615776fbae)
The reason for the error here is that test_iteration does not correspond, but should i notice this error during training.

**Comment by JUNEeer** [comment]
![image](https://github.com/user-attachments/assets/4db09f04-3b3c-4fac-a410-603205f28b31)
![image](https://github.com/user-attachments/assets/fffef5be-1688-4c28-ad5f-d6635db28289)
May I ask where your forward method is defined, and whether the last two variables can be removed?

**Comment by lizhan17** [comment]
forward  should be rgbdecoder like   
research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_model.py#L66

i guess your rgb model is not returned from here 
https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_model.py#L347

**Comment by JUNEeer** [comment]
> forward should be rgbdecoder like research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_model.py#L66
> 
> i guess your rgb model is not returned from here
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_model.py#L347

i have checked my project,find that there are  syntax errors

**Comment by JUNEeer** [comment]
![image](https://github.com/user-attachments/assets/29fdadaa-e4ab-4c0d-b640-315961732984)
![image](https://github.com/user-attachments/assets/899541ab-e64f-453a-83c3-fd20b4558a0a)
rgbfunction in the json document is not always rgbv1,why you set this as rgbv1

**Comment by JUNEeer** [comment]
> ![image](https://private-user-images.githubusercontent.com/65552093/387965751-29fdadaa-e4ab-4c0d-b640-315961732984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODQwNDQsIm5iZiI6MTczMjA4Mzc0NCwicGF0aCI6Ii82NTU1MjA5My8zODc5NjU3NTEtMjlmZGFkYWEtZTRhYi00YzBkLWI2NDAtMzE1OTYxNzMyOTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA2MjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzBiYzY0ODYyMGVlODc2NjZkNzE3MzJkMGViYTI1OTllYmQ4NmI3MzY3ZjUwNzk0ZWQ0OGEwMTMxM2ZkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2uK__eyTNgyVmbBhRkQObCyQtGkf9AMTuyF8C4GEKbM) ![image](https://private-user-images.githubusercontent.com/65552093/387965997-899541ab-e64f-453a-83c3-fd20b4558a0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODQwNDQsIm5iZiI6MTczMjA4Mzc0NCwicGF0aCI6Ii82NTU1MjA5My8zODc5NjU5OTctODk5NTQxYWItZTY0Zi00NTNhLTgzYzMtZmQyMGI0NTU4YTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA2MjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4M2Q4OTJhOTRiOGM4NjY2MmNhOTczOWY5ZmJmYzdkNzk0OWQyNzQwMjViNTUwODgzNWJmZGQ1NmJiMDFhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7cPKDrxb4I3MjzPbtX8NmTx1kUDmniCmepNgxM6Ys9I) rgbfunction in the json document is not always rgbv1,why you set this as rgbv1
Can I change it to other options, for example sandwich

**Comment by lizhan17** [comment]
rgbv1 is an old default model. 
please use sandwich* (means we have three layer of contents for mlp)
