### ISSUE TITLE
Filenotfound error colmap

### ISSUE THREAD

**Issue by Caquita-beep** [oppo-us-research/SpacetimeGaussians#9]
Hello

When running train.py, I'm getting:

Traceback (most recent call last):
  File "./thirdparty/gaussian_splatting\scene\dataset_readers.py", line 768, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
  File "./thirdparty/gaussian_splatting\scene\colmap_loader.py", line 175, in read_extrinsics_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\SpacetimeGaussians\\data\\cut_roasted_beef\\colmap_0\\sparse/0\\images.bin'

Same with "sparse/0/images.txt"

The colmap_0 (and the rest of) folders r generated by pre_n3d.py. There is no "0" folder within colmap_0 and "sparse" folders is generated within distorted and it's empty.

Not sure what is going on. Any ideas?

**Comment by lizhan17** [comment]
Hi, training, testing and preprocessing are tested on Ubuntu 20.04. More efforts are needed for windows. (like slash in windows..).
I recommend that you can use Ubuntu for training. (scripts use Ubuntu file path convention )

**Comment by Caquita-beep** [comment]
Hello. Yeah I noticed. Had errors with pre_n3d.py becuase of the "slash" and as soon as I changed to / it worked hehe but I guess it didn't as it's giving the wrong output?

**Comment by lizhan17** [comment]
> Hello. Yeah I noticed. Had errors with pre_n3d.py becuase of the "slash" and as soon as I changed to / it worked hehe but I guess it didn't as it's giving the wrong output...

you may need be carefull with other parts like... 

https://github.com/oppo-us-research/SpacetimeGaussians/blob/2f56210489ca115dc006c3400cc54750b2d38622/script/pre_n3d.py#L79

**Comment by Caquita-beep** [comment]
Hello. Turns out for some reason Colmap installation with conda is having issues and so the "getcolmapsinglen3d" function in helper3dg.py was exiting prematurelly. So I run colmap from another env (which is not installed in the env lol but on the machine) and colmap is wokring this time. However, I'm getting error on triangulation :

==============================================================================
Loading model
==============================================================================


==============================================================================
Loading database
==============================================================================

Loading cameras... 21 in 0.000s
Loading matches... 0 in 0.000s
Loading images... 21 in 0.000s (connected 0)
Building correspondence graph... in 0.000s (ignored 0)
...
...
==============================================================================
Bundle adjustment
==============================================================================

F20240104 14:56:36.840480 42368 sfm.cc:473] Check failed: bundle_adjuster.Solve(&reconstruction)
*** Check failure stack trace: ***
    @   00007FFAB66F6E5B  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFAB66F5739  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF64F621E37  (unknown)
    @   00007FF64F621360  (unknown)
    @   00007FF64F5D65E6  (unknown)
    @   00007FF64F5D7DEB  (unknown)
    @   00007FF64FBC43B4  (unknown)
    @   00007FFADA4A257D  BaseThreadInitThunk
    @   00007FFADABEAA58  RtlUserThreadStart

Any clues?

**Comment by lizhan17** [comment]
Hello,

Training, Testing and preprocessing have been tested on Ubuntu 20.04. While our efforts have been focused on this system,  much more efforts are need for other system.

We recommend that you use colmap with conda-forge.

**Comment by lizhan17** [comment]
For compatibility with Windows, we are busy dealing with other issues, and will try to adapt to Windows later. Please stay tuned for that.

**Comment by YimjuneLiu** [comment]
> > Hello. Yeah I noticed. Had errors with pre_n3d.py becuase of the "slash" and as soon as I changed to / it worked hehe but I guess it didn't as it's giving the wrong output...
> 
> you may need be carefull with other parts like...
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/2f56210489ca115dc006c3400cc54750b2d38622/script/pre_n3d.py#L79
> 
> and somecodes in the
> 
> https://github.com/oppo-us-research/SpacetimeGaussians/blob/2f56210489ca115dc006c3400cc54750b2d38622/thirdparty/gaussian_splatting/helper3dg.py#L181

`
def convertdynerftocolmapdb(path, offset=0):
    originnumpy = os.path.join(path, "poses_bounds.npy")
    video_paths = sorted(glob.glob(os.path.join(path, 'cam*.mp4')))
    projectfolder = os.path.join(path, "colmap_" + str(offset))
    #sparsefolder = os.path.join(projectfolder, "sparse/0")
    manualfolder = os.path.join(projectfolder, "manual")

    # if not os.path.exists(sparsefolder):
    #     os.makedirs(sparsefolder)
`
In this code block, Is the commented-out part the reason why the sparse is not found?

**Comment by lizhan17** [comment]
No, the commented-out part is not the reason why the sparse is not found. if the ```colmap``` can run correctly, the sparse folder will be created by ```colmap```   
the function 

I found this Pull request on 3D gaussian that may help you. 

https://github.com/graphdeco-inria/gaussian-splatting/pull/276

I remeber there will be other parts that with "/" , you may need handling other parts.

**Comment by lizhan17** [comment]
No, the sparse folder will be created by ```colmap```

If ```colmap``` cannot produce the sparse model, the sparse folder will not be found. 

what is your python version for colmap

**Comment by YimjuneLiu** [comment]
> No, the sparse folder will be created by `colmap`
> 
> If `colmap` cannot produce the sparse model, the sparse folder will not be found.
> 
> what is your python version for colmap

It's the same as yours. python 3.8.18, pytorch 1.12.1, cudatoolkit 11.6.0.

**Comment by lizhan17** [comment]
First you can confirm that colmap is installed with
```colmap -h```
if there is issue with mpir
```
# for windows run colmap 
conda install conda-forge::mpir
```
after that, you can change the 
code [https://github.com/oppo-us-research/SpacetimeGaussians/blob/a977e11cc52a56ac670046049c9d76c151000984/script/pre_n3d.py#L79](url)
to 
```imagesavepath = os.path.join(savedir, os.path.basename(os.path.dirname(folder)) + ".png")```

the command in the command prompt should be like
```
python script\pre_n3d.py --videopath C:\Users\xxxx\coffee_martini
```
python should handle the cross platform.

**Comment by YimjuneLiu** [comment]
Thank you for your reply! 

But this problem still exists. It did not generate the sparse folder.

Otherwise, python can use 
```python
python script/pre_n3d.py --videopath ../xxxx/cook_spinach
```
for windows.

**Comment by lizhan17** [comment]
> ```
> python script\pre_n3d.py --videopath C:\Users\xxxx\coffee_martini
> ```
can you try this one
```python script\pre_n3d.py --videopath C:\Users\xxxx\coffee_martini```

as python will handle the slash

**Comment by YimjuneLiu** [comment]
I tried that. 

But when I input 
```shell
python pre_n3d.py --videopath E:\Spacetime Gaussian Feature Splatting\datasets\cook_spinach
```
the Error shows as follows:
```shell
usage: pre_n3d.py [-h] [--versionpath VIDEOPATH] [--startframe STARTFRAME] [--endframe ENDFRAME]
pre_n3d.py: error: unrecognized arguments: Gaussian Feature Splatting\datasets\cook_spinach
```

**Comment by YimjuneLiu** [comment]
But it still hasn't generated the sparse folder.

**Comment by lizhan17** [comment]
> But it still hasn't generated the sparse folder.

1) can you remove all the colmap_x folders and rerun the code ?
2) can you help me verify that each ```input``` folder under the ```colam_x``` folder contain the same number of frames as the number of cameras ?

**Comment by lizhan17** [comment]
We have an update for WSL (Windows Subsystem for Linux) available for Windows users. If you encounter any issues with WSL, please feel free to reopen or open an issue.
