### ISSUE TITLE
Does SpacetimeGaussians also work for monocular videos?

### ISSUE THREAD

**Issue by haliphinx** [oppo-us-research/SpacetimeGaussians#92]
SpacetimeGaussians is a great work, thanks for open-source it.

If I understand the entire pipeline correct. The preprocessing would generate a colmap pointcloud for each timestep separately, which requires at least two cameras.

I'm wondering if SpacetimeGaussians can work under a monocular camera setup please?

**Comment by haliphinx** [comment]
nvm, just found the answer, thanks

**Comment by haliphinx** [comment]
I saw the authors reply under other issues that using i.e. 4dgs or d3dgs to get initial points. I'm wondering if the code for transfering the result from 4dgs to SpacetimeGaussians available for sharing please?

**Comment by lizhan17** [comment]
3dgs is explict point models. it is naively supported by train and reloading and training. here is some old code for reload ourself
https://github.com/oppo-us-research/SpacetimeGaussians/blob/3213738943392b9a0a96ece1ab40cf993021aaa8/helper_train.py#L313

 
I didn't try transfer from other points to our stgs except colmap and ourself. But as long as you have point's xyz and its color, you can easily convert to our model or any point models. 

You can see colmap sparse point as one step of get point model (train a model is equivalatent to using colmap reconstruct a point model). Check how our method or 3dgs init from colmap model.

**Comment by haliphinx** [comment]
Thanks for the fast rely. I noticed under one [issue](https://github.com/oppo-us-research/SpacetimeGaussians/issues/6#issuecomment-2044127013) you mentioned that the dataloader from 4dgs can be modified to load monocular video. I'm kindly wondering if that part of code is shareable? Your STGS works great and I want to try it on monocular setups.

**Comment by lizhan17** [comment]
it did not very well with monocular loader of nerfies. i used the nerfies loader from 4dgs. i guess train.py should be modified also.

**Comment by haliphinx** [comment]
Thanks for your answer. That helps a lot.
